### ISSUE TITLE
add upgrade-charm command to testing document

### ISSUE THREAD

**Issue by mbruzek** [mbruzek/docs#18]
the authors-testing-* document needs to be added to the new developer testing document

**Comment by chuckbutler** [comment]
i think this was with regard to juju upgrade-charm --force during the dev cycle maybe?

**Comment by mbruzek** [comment]
Actually the testing document is more about how to write tests than running `upgrade-charm`. There is enough content from the "authors" doc to warrant an entire document just to `upgrade-charm` as seen in #34.
